name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: sssssssxiamian
    - run: cd ..
    - run: sudo apt-get install libboost-dev
    - run: wget http://www.colm.net/files/ragel/ragel-6.10.tar.gz
    - run: tar -zxf ragel-6.10.tar.gz
    - run: cd ./ragel-6.10
    - run: sudo ./configure
    - run: sudo make -j16
    - run: sudo make install
    - run: cd ../
    - run: wget https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.gz
    - run: tar -zxvf pcre-8.41.tar.gz
    - run: sudo cp -rf ./pcre-8.41 ./hyperscan/pcre
    - run: cd ./hyperscan
    - run: rm -rf build
    - run: mkdir build
    - run: cd build
    - run: cmake ..
    - run: make -j8
